<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\PuppyWorld.Application\PuppyWorld.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\PuppyWorld.Infrastructure\PuppyWorld.Infrastructure.csproj" />
  </ItemGroup>

</Project>
